### ISSUE TITLE
Week 1 Paper: When Scientists Choose Motherhood

### ISSUE THREAD

**Issue by clarrain** [DeveloperLiberationFront/ExploringGHTorrent#5]
The paper discusses the impact of female scientists choosing to leave a profession in order to have children on the number of women who are assistant/associate/full professors in the science and math-based fields. I'm using the ideas expressed in this paper to consider recent statistics that were discovered by the team: seemingly more men than women have pictures of their children on their GitHub accounts. 

Williams, Wendy M., and Stephen J. Ceci. "When Scientists Choose Motherhood." American Scientist 100.2 (2012): 138-45. Student Research Center. Web. 7 Jan. 2016.

**Comment by clarrain** [comment]
Questions to explore further:
If there are considerably less females than males with higher levels of education in CS, would that mean that women are less "qualified" than most men in CS? If so, why are females' pull requests getting accepted more (just makes the data even more surprising to me).
Find some sort of stat that compares number of fathers to number of mothers in CS field - could mean that the results proving more men have photos with children on GitHub isn't relevant since more men have children in the field in general.

**Comment by clarrain** [comment]
![20121301742428924-2012-03williamsf6](https://cloud.githubusercontent.com/assets/13869747/12184806/86834e32-b565-11e5-928a-bb61b415412e.jpg)
Some interesting stats in this article provided by research from D. W. Leslie, 2007 - to be explored further

**Comment by CaptainEmerson** [comment]
> more men have children in the field in general.

But do male _developers_ have children more often (especially open source developers)? The above article seems to be about professors, who are an odd bunch. :smirk: 

I'll bet you can piece together some data from various open source surveys that have been conducted. You can start here: http://floss2013.libresoft.es/

**Comment by clarrain** [comment]
## Male/Female Children Statistics

_Taken from 2013 FLOSS Survey_

### Numbers:

Total number of records: 2183

Number of males surveyed: 1776
Number of females surveyed: 226

Number of males **with** children: 597
Number of males **without** children: 1158
Number of males who did not respond: 21

Number of females **with** children: 46
Number of females **without** children: 178 
Number of females who did not respond: 2

### Percentages:

Percent of survey takers that were male: 81.36%
Percent of survey takers that were female: 10.35%

Percent of males **with** children: 33.61%
Percent of males **without** children: 65.20%
Percent of males who did not respond: 1.18%

Percent of females **with** children: 20.35%
Percent of females **without** children: 78.76%
Percent of females who did not respond: 0.88%

**Comment by clarrain** [comment]
In terms of the gender numbers: 
33 people responded "Other" 
32 people responded "No answer"
116 people did not complete the question 

That makes up for the missing 181 records in the total after subtracting out the number of males and females :blush:

**Comment by CaptainEmerson** [comment]
Thanks, used it. Also, remind me to talk to you about peer-reviewed articles.
