### ISSUE TITLE
Week 2 Paper: Ambient Belonging

### ISSUE THREAD

**Issue by clarrain** [DeveloperLiberationFront/ExploringGHTorrent#6]
Just realized that I finished writing the notes for this and never submitted it as an issue. 
Paper is [here](http://sciencewithart.ijs.si/pdf/How%20stereotypical%20cues%20impact%20gender%20participation%20in%20computer%20science.pdf)
A compilation of four studies that examined how the surrounding environment can influence women's perceptions of their relation to computer science. Though this paper focused on the physical environment, I am using it to consider the effects of a digital environment, such as the interactions on GitHub. 

The idea I mentioned briefly of the presentation of politeness ("Thanks!" versus "Thanks.") was generated by this paper. I'm in the process of examining the patterns between the variations of thank you and considering other instances where the interactions of the digital environment could be discouraging.

**Comment by clarrain** [comment]
Actually the more that I look at this, the more I think I may be getting off track from the original issues of the paper...straying into "why women aren't in CS" instead of "why women's pull requests are more accepted on GitHub" 
I'll focus my efforts more on the issue we discussed last week (likelihood for a male/female to make a second pull request on the same project if their first pull request is closed) because that ties more directly into the purpose of the research while still considering environment

**Comment by CaptainEmerson** [comment]
:+1:
